(library
 (name gk_tools)
 (libraries
  core
  core_unix
  core_unix.bigstring_unix
  core_unix.linux_ext
  core_unix.time_ns_unix
  async
  async_interactive
  async_ssl
  cohttp
  cohttp-async
  file_path
  filesystem.async
  jsonaf
  re
  uri
  sexp_macro
  xdg
  patdiff
  patdiff.kernel)
 (foreign_stubs
  (language cxx)
  (names dnf_native_stubs)
  (flags
   (:standard -std=c++20 -Werror=switch -DFMT_HEADER_ONLY)))
 (c_library_flags
  (-ldnf5 -lstdc++))
 (preprocess
  (pps ppx_jane ppx_jsonaf_conv)))
